### ISSUE TITLE
 AttributeError: 'dict' object has no attribute 'split' ---- File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385,

### ISSUE THREAD

**Issue by JunaidChaudry** [Merck/Mutation_Maker#13]
When running mutation-maker on docker, using primer3 with the following payload fails, giving the following stackTrace

``` | [2021-02-09 00:09:17,837: ERROR/ForkPoolWorker-3] Task tasks.ssm[d82fd8e6-6908-4ee2-a99b-9f7e2d503429] raised unexpected: AttributeError("'dict' object has no attribute 'split'")
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
worker_1     |     R = retval = fun(*args, **kwargs)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
worker_1     |     return self.run(*args, **kwargs)
worker_1     |   File "/mutation_maker/tasks.py", line 52, in ssm
worker_1     |     return ssm_solve(input, main_generator, secondary_generator)
worker_1     |   File "/mutation_maker/mutation_maker/ssm.py", line 67, in ssm_solve
worker_1     |     result = solver.solve_for_mutations(mutations,flanks)
worker_1     |   File "/mutation_maker/mutation_maker/ssm.py", line 273, in solve_for_mutations
worker_1     |     self.generate_primers(mutations, self.main_primer_generator, "main")
worker_1     |   File "/mutation_maker/mutation_maker/ssm.py", line 202, in generate_primers
worker_1     |     fw_lists, rw_lists = self.generate_fw_rw_primers(mutations, primer_generator)
worker_1     |   File "/mutation_maker/mutation_maker/ssm.py", line 187, in generate_fw_rw_primers
worker_1     |     results = primer_generator.design_primers_for_all_mutations(all_configs)
worker_1     |   File "/mutation_maker/mutation_maker/primer3_interoperability.py", line 166, in design_primers_for_all_mutations
worker_1     |     return self.design_multiple_lambda_primers(config_list)
worker_1     |   File "/mutation_maker/mutation_maker/primer3_interoperability.py", line 171, in design_multiple_lambda_primers
worker_1     |     return [parse_primers(_parseBoulderIO(result)) for result in results]
worker_1     |   File "/mutation_maker/mutation_maker/primer3_interoperability.py", line 171, in <listcomp>
worker_1     |     return [parse_primers(_parseBoulderIO(result)) for result in results]
worker_1     |   File "/mutation_maker/mutation_maker/primer3_interoperability.py", line 41, in _parseBoulderIO
worker_1     |     for line in boulder_str.split('\n'):
worker_1     | AttributeError: 'dict' object has no attribute 'split'
```

STEPS to reproduce: 
- run on docker by starting the project using docker-compose up --build. 
- Use primer3 option and the following payload:
  

> -1. 1)	Plasmid Sequence:
> AGTAGTAGGTTGAGGCCGTTGAGCACCGCCGCCGCAAGGAATGGTGCATGCAAGGAGATGGCGCCCAACAGTCCCCCGGCCACGGGGCCTGCCACCATACCCACGCCGAAACAAGCGCTCATGAGCCCGAAGTGGCGAGCCCGATCTTCCCCATCGGTGATGTCGGCGATATAGGCGCCAGCAACCGCACCTGTGGCGCCGGTGATGCCGGCCACGATGCGTCCGGCGTAGAGGATCGAGATCGATCTCGATCCCGCGAAATTAATACGACTCACTATAGGGGAATTGTGAGCGGATAACAATTCCCCTCTAGAAATAATTTTGTTTAACTTTAAGAAGGAGATATACATATGCACCACCACCACCACCACTCAGCTGGAGCAGGGAGTCACTGTCAAAAAACCAGCCTGCGTGTGAACTTCGAGGACATCGGTTGGGATAGCTGGATCATTGCGCCGAAGGAGTACGAAGCGTATGAATGCAAAGGTGGCTGCTTCTTTCCGCTGGCGGACGATGTTACCCCGACCAAACACGCGATCGTGCAAACCCTGGTTCACCTGAAGTTTCCGACCAAAGTGGGTAAAGCGTGCTGCGTTCCGACCAAGCTGAGCCCGATTAGCGTGCTGTACAAAGACGATATGGGCGTTCCGACCCTGAAGTACCACTATGAGGGTATGAGCGTGGCGGAATGCGGCTGCCGTTAATAAGAATTCGAGCTCCGTCGACAAGCTTGCGGCCGCACTCGAGCACCACCACCACCACCACTGAGATCCGGCTGCTAACAAAGCCCGAAAGGAAGCTGAGTTGGCTGCTGCCACCGCTGAGCAATAACTAGCATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGCTGAAAGGAGGAACTATATCCGGATTGGCGAATGGGACGCGCCCTGTAGCGGCGCATTAAGCGCGGCGGGTGTGGTGGTTACGCGCAGCGTGACCGCTACACTTGCCAGCGCCCTAGCGCCCGCTCCTTTCGCTTTCTTCCCTTCCTTTCTCGCCACGTTCGCCGGCTTTCCCCGTCAAGCTCTAAATCGGGGGCTCCCTTTAGGGTTCCGATTTAGTGCTTTACGGCACCTCGACCCCAAAAAACTTGATTAGGGTGATGGTTCACGTAGTGGGCCATCGCCCTGATAGACGGTTTTTCGCCCTTTGACGTTGGAGTCCACGTTCTTTAATAGTGGACTCTTGTTCCAAACTGGAACAACACTCAACCCTATCTCGGTCTATTCTTTTGATTTATAAGGGATTTTGCCGATTTCGGCCTATTGGTTAAAAAATGAGCTGATTTAACAAAAATTTAACGCGAATTTTAACAAAATATTAACGTTTACAATTTCAGGTGGCAC
> 2)	Sequence:
> ATGCACCACCACCACCACCACTCAGCTGGAGCAGGGAGTCACTGTCAAAAAACCAGCCTGCGTGTGAACTTCGAGGACATCGGTTGGGATAGCTGGATCATTGCGCCGAAGGAGTACGAAGCGTATGAATGCAAAGGTGGCTGCTTCTTTCCGCTGGCGGACGATGTTACCCCGACCAAACACGCGATCGTGCAAACCCTGGTTCACCTGAAGTTTCCGACCAAAGTGGGTAAAGCGTGCTGCGTTCCGACCAAGCTGAGCCCGATTAGCGTGCTGTACAAAGACGATATGGGCGTTCCGACCCTGAAGTACCACTATGAGGGTATGAGCGTGGCGGAATGCGGCTGCCGTTAA
> 
> 3)	Mutation
> H2X	H3X	H4X

![image](https://user-images.githubusercontent.com/49313431/107297674-dbeb9500-6a41-11eb-9777-cab445b26a2d.png)

**Comment by JunaidChaudry** [comment]
Any updates on this please? @spalemartin @prihoda  @ra100

**Comment by ra100** [comment]
Sorry I have currently issues running it at all locally.

**Comment by ra100** [comment]
I think the issue is in the lambda process:
```log
lambda_1     | START RequestId: 6e7921ed-1a86-18e7-6294-875300a50f67 Version: $LATEST
lambda_1     | [Errno 2] No such file or directory: '/var/task/primer3_core': '/var/task/primer3_core': FileNotFoundError
lambda_1     | Traceback (most recent call last):
lambda_1     |   File "/var/task/lambda_function.py", line 39, in lambda_handler
lambda_1     |     stderr=subprocess.STDOUT)
lambda_1     |   File "/var/lang/lib/python3.6/subprocess.py", line 729, in __init__
lambda_1     |     restore_signals, start_new_session)
lambda_1     |   File "/var/lang/lib/python3.6/subprocess.py", line 1364, in _execute_child
lambda_1     |     raise child_exception_type(errno_num, err_msg, err_filename)
lambda_1     | FileNotFoundError: [Errno 2] No such file or directory: '/var/task/primer3_core': '/var/task/primer3_core'
```

As, if I remember correctly, primer3 is computed on lambdas

**Comment by JunaidChaudry** [comment]
Yes, primer3 does require lambda. However if you run it in docker along with lambda docker (i believe it uses sam cli), the above error is coming up... Don't know myself where the issue is, hence reaching out to you guys

**Comment by ra100** [comment]
Maybe I found what is the issue.
Can you run?
```
cd lambda
make
```

And then rerun docker compose?

**Comment by JunaidChaudry** [comment]
That works... But is there a way to do it as part of one command, or one dockerfile? 
I am trying to deploy it on a kubernetes cluster, which can use a docker image and can do a docker build, but can't really a docker build in another docker build... 
So like will this work fine if I add the makefile and dockerfile content in the lambda directory as part of the main lambda dockerfile, or some other thing to make it really one command, rather than first going to `cd lambda`, followed by `make` and then going back and doing a `docker-compose up --build`?

**Comment by prihoda** [comment]
After running `make`, I guess you could commit the created files to the repository, so that they are available by default. Would that work @ra100 @spalemartin?

**Comment by ra100** [comment]
I think it will solve the issue, temporarily, as the file will have to be updated next time lambda folder changes.

**Comment by ra100** [comment]
@JunaidChaudry I've tried to create primer3 image and pushed to docker hub, can you try to replace the lambda part of docker-compose with this?

```yaml
lambda:
    image: ra100/mutation-maker-primer3:dev-4d814b6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SAM_CLI_TELEMETRY=0
    ports:
      - '3001'
    command: sam local start-lambda --docker-volume-basedir "$PWD/lambda" --skip-pull-image --host 0.0.0.0
    networks:
      - local
```

**Comment by JunaidChaudry** [comment]
That did not work @ra100 .. It gives the same error that you get when not doing `cd lambda` and `make`

**Comment by ra100** [comment]
Can you try this?
```yaml
version: '3.4'
services:
  # API provides an API that schedules and monitors tasks
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - worker
    networks:
      - local
  # Worker provides a Celery worker that processes tasks from the Redis queue
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - RUN_LAMBDA_DOCKER=1
      - LAMBDA_FN_NAME
    depends_on:
      - redis
      - lambda
    networks:
      - local
  # Redis provides Redis in-memory database that serves as a queue for Celery tasks
  redis:
    image: redis:6-alpine
    ports:
      - '6379'
    networks:
      - local
  # Frontend provides the frontend React server that communicates with the API
  # It is exposed only through the Webserver service
  frontend:
    build:
      context: ./frontend
      # Select live-reload-server target for the development npm server with live reload
      #      target: live-reload-server
      # Select the production-server target for the production-ready Nginx server with built artifacts
      target: production-server
    volumes:
      - ./frontend/public:/frontend/public
      - ./frontend/src:/frontend/src
    depends_on:
      - api
    networks:
      - local
  # Webserver is the main entry point for the user, proxying "/v1" requests to the API and all remaining requests to the frontend
  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - frontend
      - api
    networks:
      - local
  # Lambda is a container for local AWS Lambda function execution by SAM CLI: https://github.com/awslabs/aws-sam-cli
  lambda:
    image: ra100/mutation-maker-primer3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SAM_CLI_TELEMETRY=0
    ports:
      - '3001'
    command: sam local start-lambda --docker-volume-basedir "$PWD/lambda" --skip-pull-image --host 0.0.0.0
    networks:
      - local
networks:
  local:
```
